extends Node
## Client-side SFX + ambient layer.  Listens to the Events bus and plays
## procedurally-generated WAV sounds in reaction to gameplay.
## Mirrors AssetRegistry's guarded-fallback pattern: a missing file is
## skipped silently so the game ALWAYS runs with zero audio assets.
##
## Audio is purely local: it only reads the (already-replicated) Events
## signals, never networks anything itself.
## HEADLESS SAFETY: all looping bed players + UI-button wiring are
## guarded by DisplayServer.get_name() != "headless" so dedicated servers
## never touch audio hardware.

# ---------------------------------------------------------------------------
# Sound map — logical id -> res path (all .wav; generated by tools/audio/gen_audio.py)
# ---------------------------------------------------------------------------
# Minor SFX (UI/extract/jingles/footsteps/heartbeat/reload/hit/explosion) are CC0
# procedural clips from tools/audio/gen_audio.py. The GUNSHOTS and the two looping
# BEDS (ambient, music) are REAL CC0 recordings fetched by tools/audio/fetch_real_audio.ps1
# (see docs/ASSETS.md → Audio). Per-class gunshots are distinct recorded firearms.
const SOUNDS := {
	# Per-weapon-class gunshots — real CC0 firearm recordings (OpenGameArt "Gunshot Sounds").
	"shot_pistol": "res://assets/audio/shot_pistol.wav",  # CZ-52 pistol
	"shot_rifle": "res://assets/audio/shot_rifle.wav",  # SKS (semi-auto rifle)
	"shot_smg": "res://assets/audio/shot_smg.wav",  # CZ-52 (reused, pitched up)
	"shot_shotgun": "res://assets/audio/shot_shotgun.wav",  # shotgun
	"shot_dmr": "res://assets/audio/shot_dmr.wav",  # Mosin Nagant (bolt-action boom)
	"shot": "res://assets/audio/shot_rifle.wav",  # generic fallback
	"hit": "res://assets/audio/hit.ogg",
	"explosion": "res://assets/audio/explosion.ogg",
	"player_death": "res://assets/audio/player_death.ogg",
	"extract_beep": "res://assets/audio/extract_beep.ogg",
	"extract_done": "res://assets/audio/extract_done.ogg",
	"extract_cancel": "res://assets/audio/extract_cancel.ogg",
	"wave_alert": "res://assets/audio/wave_alert.ogg",
	"win": "res://assets/audio/win.ogg",
	"lose": "res://assets/audio/lose.ogg",
	# New
	"footstep1": "res://assets/audio/footstep1.ogg",
	"footstep2": "res://assets/audio/footstep2.ogg",
	"footstep3": "res://assets/audio/footstep3.ogg",
	"reload": "res://assets/audio/reload.ogg",
	"weapon_switch": "res://assets/audio/weapon_switch.ogg",
	"ui_click": "res://assets/audio/ui_click.ogg",
	"heartbeat": "res://assets/audio/heartbeat.ogg",
	"ambient": "res://assets/audio/ambient.ogg",
	"music": "res://assets/audio/music.ogg",
	# Water immersion (Lane B): entry splash + looping submerged ambience.
	"water_splash": "res://assets/audio/water_splash.ogg",
	"underwater": "res://assets/audio/underwater.ogg",
	# Breakable windows (interactivity overhaul).
	"glass_break": "res://assets/audio/glass_break.wav",
	# Material-typed building/rock collapse (Destruction 2.1).
	"chunk_concrete": "res://assets/audio/chunk_concrete.wav",
	"chunk_metal": "res://assets/audio/chunk_metal.wav",
	"chunk_stone": "res://assets/audio/chunk_stone.wav",
	# Production audio pass: biome ambient beds + robot vocalizations (gen_audio.py).
	"amb_urban": "res://assets/audio/amb_urban.ogg",
	"amb_snow": "res://assets/audio/amb_snow.ogg",
	"amb_desert": "res://assets/audio/amb_desert.ogg",
	"amb_rain": "res://assets/audio/amb_rain.ogg",
	"robot_alert": "res://assets/audio/robot_alert.ogg",
	"robot_death": "res://assets/audio/robot_death.ogg",
	# 96 s evolving dark loop (gen_music_long) — swapped in when the STORM hits.
	"music_storm": "res://assets/audio/music_storm.ogg",
	# M1 music layers: percussive combat overlay stem faded in while machines fight.
	"music_combat": "res://assets/audio/music_combat.ogg",
	# MOBA skill rework (v0.4.5): per-ability cast/impact sounds (gen_audio.py).
	"skill_cast": "res://assets/audio/skill_cast.wav",
	"skill_meteor": "res://assets/audio/skill_meteor.wav",
	"skill_storm": "res://assets/audio/skill_storm.wav",
	"skill_leap": "res://assets/audio/skill_leap.wav",
	"skill_slam": "res://assets/audio/skill_slam.wav",
	"skill_breach": "res://assets/audio/skill_breach.wav",
	"skill_zap": "res://assets/audio/skill_zap.wav",
}

## Per-sound volume trim (dB).  Unlisted sounds play at 0 dB.
const SOUND_DB := {
	# Real firearm recordings are hot/peaky — trim them well down so they punch
	# without clipping. Per-class trims layer on top of these (SHOT_CLASS.vol).
	"shot_pistol": -10.0,
	"shot_rifle": -11.0,
	"shot_smg": -12.0,
	"shot_shotgun": -6.0,
	"shot_dmr": -8.0,
	"shot": -11.0,
	"hit": -4.0,
	"explosion": -3.0,
	"player_death": 0.0,
	"win": -2.0,
	"lose": -2.0,
	"footstep1": -12.0,
	"footstep2": -12.0,
	"footstep3": -12.0,
	"reload": -6.0,
	"weapon_switch": -8.0,
	"ui_click": -10.0,
	"heartbeat": -14.0,
	"ambient": -18.0,
	"music": -20.0,
	"water_splash": -5.0,
	"underwater": -12.0,
	"glass_break": -6.0,
	"chunk_concrete": -5.0,
	"chunk_metal": -6.0,
	"chunk_stone": -7.0,
	"robot_alert": -9.0,
	"robot_death": -7.0,
	"skill_cast": -8.0,
	"skill_meteor": -5.0,
	"skill_storm": -8.0,
	"skill_leap": -7.0,
	"skill_slam": -4.0,
	"skill_breach": -6.0,
	"skill_zap": -7.0,
}

# In-raid ambient bed per biome (the base "ambient" wind is the fallback + menu bed).
const _AMB_BY_BIOME := {
	"urban": "amb_urban",
	"snow": "amb_snow",
	"desert": "amb_desert",
	"rain": "amb_rain",
}

## Master toggle + trim.  Public so a settings menu can drive them later.
var enabled := true
var master_db := -3.0

# Ducking (M1 audio mix): loud one-shots dip the "Bed" bus (music+ambient), then
# it recovers at ~26 dB/s — combat reads punchy without a manual mix pass.
var _duck_db: float = 0.0
var _bed_bus_idx: int = -1

# M1 music layers: the combat percussion stem rides OVER the calm bed, mixed by
# live threat (any machine in CHASE/ATTACK within 45 m). Own player — never
# touched by the storm-swap tweens.
var _combat_player: AudioStreamPlayer = null
var _combat_mix: float = 0.0
var _combat_poll: float = 0.0
var _combat_hot: bool = false

# M1 reverb zones: one-shots live on an "SFX" bus whose reverb wet/room blends
# between OUTDOOR (airy, low) and INDOOR (roomy) from a ceiling raycast.
var _sfx_bus_idx: int = -1
var _reverb: AudioEffectReverb = null
var _indoor_mix: float = 0.0
var _indoor_target: float = 0.0
var _indoor_poll: float = 0.0


## Duck the music/ambient bed by `db` (negative). Deeper requests win.
func duck(db: float) -> void:
	_duck_db = minf(_duck_db, db)


## Combat music layer: fade the percussion stem in while any machine actively
## fights the local player (CHASE/ATTACK within 45 m), out ~4× slower.
func _tick_combat_layer(delta: float) -> void:
	if _combat_player == null:
		return
	var in_combat := false
	if (
		_local_player != null
		and is_instance_valid(_local_player)
		and GameState.phase == GameState.Phase.IN_MATCH
	):
		_combat_poll -= delta
		if _combat_poll <= 0.0:
			_combat_poll = 0.5
			_combat_hot = false
			var ppos: Vector3 = (_local_player as Node3D).global_position
			for e in get_tree().get_nodes_in_group("enemies"):
				if not (e is Node3D):
					continue
				var st: int = int(e.get("current_state")) if "current_state" in e else 0
				if st != 1 and st != 2:
					continue
				if (e as Node3D).global_position.distance_to(ppos) <= 45.0:
					_combat_hot = true
					break
		in_combat = _combat_hot
	var rate: float = 1.6 if in_combat else 0.35
	_combat_mix = clampf(_combat_mix + (1.0 if in_combat else -1.0) * rate * delta, 0.0, 1.0)
	if _combat_mix <= 0.01:
		if _combat_player.playing:
			_combat_player.stop()
		return
	if not _combat_player.playing:
		_combat_player.play()
	_combat_player.volume_db = lerpf(-46.0, -9.0, _combat_mix)


## Reverb-zone blend: a ceiling above the player → INDOOR (roomier, wetter).
func _tick_reverb_zone(delta: float) -> void:
	if _reverb == null or _local_player == null or not is_instance_valid(_local_player):
		return
	_indoor_poll -= delta
	if _indoor_poll <= 0.0:
		_indoor_poll = 1.0
		var body := _local_player as Node3D
		if body != null and body.is_inside_tree():
			var space := body.get_world_3d().direct_space_state
			var from: Vector3 = body.global_position + Vector3.UP * 0.6
			var q := PhysicsRayQueryParameters3D.create(from, from + Vector3.UP * 8.0, 1)
			var hit: Dictionary = space.intersect_ray(q)
			_indoor_target = 1.0 if not hit.is_empty() else 0.0
	_indoor_mix = lerpf(_indoor_mix, _indoor_target, clampf(2.5 * delta, 0.0, 1.0))
	_reverb.wet = lerpf(0.06, 0.3, _indoor_mix)
	_reverb.room_size = lerpf(0.3, 0.72, _indoor_mix)


# ---------------------------------------------------------------------------
# Shot throttle (weapon_fired fires ~8/s in full auto)
# ---------------------------------------------------------------------------
const SHOT_MIN_INTERVAL := 0.05
var _last_shot_time := -1.0

# Crumble SFX throttle: a grenade/burst snaps many cells in one frame → play 1-2 layered crumbles,
# not 14. material_kind (0/1/2) selects the sound.
var _last_chunk_sfx_time := -1.0
const _CHUNK_SFX_BY_KIND := ["chunk_concrete", "chunk_metal", "chunk_stone"]

# ---------------------------------------------------------------------------
# Stream cache (null when the file is absent)
# ---------------------------------------------------------------------------
var _streams: Dictionary = {}

# ---------------------------------------------------------------------------
# Non-positional round-robin pool for one-shot UI / global sounds
# ---------------------------------------------------------------------------
const POOL_SIZE := 8
var _pool: Array[AudioStreamPlayer] = []
var _pool_next := 0

# ---------------------------------------------------------------------------
# Footstep state
# ---------------------------------------------------------------------------
var _local_player: Node = null
var _footstep_timer := 0.0  # countdown to next footstep
const FOOTSTEP_WALK_INTERVAL := 0.50
const FOOTSTEP_SPRINT_INTERVAL := 0.32
const FOOTSTEP_SPEED_THRESHOLD := 1.0  # horizontal m/s below which no footstep

# ---------------------------------------------------------------------------
# Low-HP heartbeat
# ---------------------------------------------------------------------------
var _heartbeat_player: AudioStreamPlayer = null
const HEARTBEAT_HP_THRESHOLD := 0.30  # ratio of max_health

# ---------------------------------------------------------------------------
# Looping ambient + music beds
# ---------------------------------------------------------------------------
var _ambient_player: AudioStreamPlayer = null
var _music_player: AudioStreamPlayer = null
# Biome-bed crossfade state: which bed id is playing + a 2 s poll of the player's biome.
var _ambient_id := ""
var _amb_poll := 0.0
var _amb_tween: Tween = null
# Underwater ambience bed + Master-bus lowpass for the muffled submerged effect.
var _underwater_player: AudioStreamPlayer = null
var _underwater_lowpass_idx := -1  # index of the lowpass effect we add to Master (-1 = none)
var _underwater_active := false
const UNDERWATER_BASE_DB := -12.0
const AMBIENT_BASE_DB := -19.0  # real wind-loop bed — quiet, atmospheric
const MUSIC_BASE_DB := -23.0  # tense dark-ambient music — deliberately quiet
const MUSIC_WAVE_DB := -18.0  # slight raise during active waves


# ---------------------------------------------------------------------------
# _ready
# ---------------------------------------------------------------------------
func _ready() -> void:
	# Cache streams; absent files resolve to null.
	for id in SOUNDS:
		var path: String = SOUNDS[id]
		if ResourceLoader.exists(path):
			var res := load(path)
			if res is AudioStream:
				_streams[id] = res
				continue
		_streams[id] = null

	# Round-robin pool for non-positional one-shots.
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.bus = "Master"
		add_child(p)
		_pool.append(p)

	# Dedicated looping players (bed tracks + heartbeat).
	_heartbeat_player = _make_looping_player("heartbeat", SOUND_DB.get("heartbeat", 0.0))
	_heartbeat_player.volume_db = -80.0  # start silent
	_heartbeat_player.playing = false

	var is_headless := DisplayServer.get_name() == "headless"

	if not is_headless:
		_ambient_player = _make_looping_player("ambient", AMBIENT_BASE_DB)
		_ambient_player.volume_db = -80.0

		_music_player = _make_looping_player("music", MUSIC_BASE_DB)
		_music_player.volume_db = -80.0

		# Underwater ambience bed (starts silent; faded in on SUBMERGED).
		_underwater_player = _make_looping_player("underwater", UNDERWATER_BASE_DB)
		_underwater_player.volume_db = -80.0

		# Wire UI click to all buttons added after this point.
		get_tree().node_added.connect(_on_node_added)

		# AUDIO MIX (M1): the music/ambient beds live on their own "Bed" bus so loud
		# one-shots can DUCK them (bus volume dip) without touching the per-player
		# volume tweens (storm crossfade etc. keep owning player.volume_db).
		_bed_bus_idx = AudioServer.bus_count
		AudioServer.add_bus(_bed_bus_idx)
		AudioServer.set_bus_name(_bed_bus_idx, "Bed")
		AudioServer.set_bus_send(_bed_bus_idx, "Master")
		_music_player.bus = "Bed"
		_ambient_player.bus = "Bed"
		_underwater_player.bus = "Bed"

		# Combat overlay stem (starts silent; mixed in _process by live threat).
		_combat_player = _make_looping_player("music_combat", -9.0)
		_combat_player.volume_db = -80.0
		_combat_player.bus = "Bed"

		# "SFX" bus with a blendable reverb (outdoor air ↔ indoor room).
		_sfx_bus_idx = AudioServer.bus_count
		AudioServer.add_bus(_sfx_bus_idx)
		AudioServer.set_bus_name(_sfx_bus_idx, "SFX")
		AudioServer.set_bus_send(_sfx_bus_idx, "Master")
		_reverb = AudioEffectReverb.new()
		_reverb.wet = 0.06
		_reverb.room_size = 0.3
		AudioServer.add_bus_effect(_sfx_bus_idx, _reverb)
		for p in _pool:
			p.bus = "SFX"

	# Events bus connections.
	Events.weapon_fired.connect(_on_weapon_fired)
	Events.damage_dealt.connect(_on_damage_dealt)
	Events.entity_died.connect(_on_entity_died)
	Events.extraction_started.connect(_on_extraction_started)
	Events.extraction_completed.connect(_on_extraction_completed)
	Events.extraction_cancelled.connect(_on_extraction_cancelled)
	Events.wave_started.connect(_on_wave_started)
	Events.match_won.connect(_on_match_won)
	Events.match_lost.connect(_on_match_lost)
	Events.grenade_exploded.connect(_on_grenade_exploded)
	Events.reload_started.connect(_on_reload_started)
	Events.weapon_switched.connect(_on_weapon_switched)
	Events.local_player_spawned.connect(_on_local_player_spawned)
	Events.player_health_changed.connect(_on_player_health_changed)
	Events.water_state_changed.connect(_on_water_state_changed)
	Events.glass_broken.connect(_on_glass_broken)
	Events.chunk_broken.connect(_on_chunk_broken)
	Events.enemy_chase_started.connect(_on_enemy_chase_started)
	Events.final_wave_started.connect(_on_final_wave)
	if Events.has_signal("match_started"):
		Events.match_started.connect(_on_match_started)


# ---------------------------------------------------------------------------
# _process — footstep ticker (independent of player input, reads velocity)
# ---------------------------------------------------------------------------
func _process(delta: float) -> void:
	# Ducking recovery runs unconditionally (a duck must release even menu-side).
	if _duck_db < 0.0 and _bed_bus_idx >= 0:
		_duck_db = minf(_duck_db + 26.0 * delta, 0.0)
		AudioServer.set_bus_volume_db(_bed_bus_idx, _duck_db)
	_tick_combat_layer(delta)
	_tick_reverb_zone(delta)
	if not enabled or _local_player == null:
		return
	if not is_instance_valid(_local_player):
		_local_player = null
		return

	# Biome ambient bed: 2 s poll of the local player's biome → crossfade the bed.
	_amb_poll -= delta
	if _amb_poll <= 0.0:
		_amb_poll = 2.0
		_update_biome_bed()

	# Footstep logic: player must be on the floor and moving.
	if not _local_player.has_method("is_on_floor"):
		return
	if not _local_player.is_on_floor():
		return

	var vel: Vector3 = _local_player.velocity if "velocity" in _local_player else Vector3.ZERO
	var horiz_speed := Vector2(vel.x, vel.z).length()
	if horiz_speed < FOOTSTEP_SPEED_THRESHOLD:
		return

	_footstep_timer -= delta
	if _footstep_timer > 0.0:
		return

	# Pick interval based on speed.
	var is_sprinting := horiz_speed > (Settings.PLAYER_SPRINT_SPEED * 0.6)
	_footstep_timer = FOOTSTEP_SPRINT_INTERVAL if is_sprinting else FOOTSTEP_WALK_INTERVAL

	# Play random variant positionally.
	var variant := "footstep%d" % (randi() % 3 + 1)
	_play_at(variant, _local_player)


# ---------------------------------------------------------------------------
# Event handlers — existing
# ---------------------------------------------------------------------------


func _on_grenade_exploded(_world_pos: Vector3, _damage: float, _radius: float) -> void:
	_play("explosion")
	duck(-8.0)


## A window pane shattered (fires on every peer) — positional tinkle at the pane.
func _on_glass_broken(pane: Node) -> void:
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	if pane is Node3D:
		_play_at("glass_break", pane)


## A building/rock chunk crumbled (fires on every peer) — a material-typed collapse boom at the
## cell. Throttled so a grenade snapping a whole section plays 1-2 layered crumbles, not 14.
func _on_chunk_broken(chunk: Node) -> void:
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	if not (chunk is Node3D):
		return
	var now := Time.get_ticks_msec() / 1000.0
	if _last_chunk_sfx_time >= 0.0 and now - _last_chunk_sfx_time < Settings.CHUNK_SFX_MIN_INTERVAL:
		return
	_last_chunk_sfx_time = now
	var kind: int = 0
	if "material_kind" in chunk:
		kind = clampi(int(chunk.material_kind), 0, 2)
	_play_at_pitched(_CHUNK_SFX_BY_KIND[kind], chunk, randf_range(0.94, 1.06))


## Per-weapon-class gunfire trim. Each class now has its OWN recorded firearm
## (shot_<class>), so this is just a light pitch nudge (SMG reuses the pistol crack,
## pitched up to read snappier) + a small volume trim on top of SOUND_DB. A tiny
## random pitch jitter is applied per shot so repeated fire never sounds identical.
const SHOT_CLASS := {
	"pistol": {"pitch": 1.0, "vol": 0.0},
	"rifle": {"pitch": 1.0, "vol": 0.0},
	"smg": {"pitch": 1.12, "vol": -1.0},
	"shotgun": {"pitch": 0.97, "vol": 0.0},
	"dmr": {"pitch": 0.98, "vol": 0.0},
}


func _on_weapon_fired(_shooter: Node, weapon_id: String) -> void:
	# Entity SFX only while a match runs — a lingering/tearing-down world must never
	# keep shooting sounds into the lobby (UI/extract/win-lose SFX stay ungated).
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	var now := Time.get_ticks_msec() / 1000.0
	if _last_shot_time >= 0.0 and now - _last_shot_time < SHOT_MIN_INTERVAL:
		return
	duck(-4.0)
	_last_shot_time = now
	var cfg: Dictionary = SHOT_CLASS.get(weapon_id, SHOT_CLASS["rifle"])
	# Route to the class-specific recorded firearm; fall back to the generic shot if
	# a class file is missing (headless / asset not present).
	var shot_id: String = "shot_" + weapon_id
	if _streams.get(shot_id, null) == null:
		shot_id = "shot"
	_play_pitched(shot_id, float(cfg["pitch"]) * randf_range(0.96, 1.04), float(cfg["vol"]))


## Like _play but with a pitch_scale + extra volume trim (for layered gunfire).
func _play_pitched(id: String, pitch: float, vol_extra: float) -> void:
	if not enabled:
		return
	var stream: AudioStream = _streams.get(id, null)
	if stream == null:
		return
	var p := _pool[_pool_next]
	_pool_next = (_pool_next + 1) % POOL_SIZE
	p.stream = stream
	p.pitch_scale = clampf(pitch, 0.2, 3.0)
	p.volume_db = master_db + SOUND_DB.get(id, 0.0) + vol_extra
	p.play()


func _on_damage_dealt(target: Node, _amount: float, _source: Node) -> void:
	# The lobby "I'm being hit" loop fix, layer 2: damage in a lingering world
	# (post-match teardown, bleed ticks) must never reach the speakers.
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	_play_at("hit", target)


func _on_entity_died(entity: Node, _killer: Node) -> void:
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	if entity != null and entity.is_in_group(Groups.PLAYERS):
		_play_at("player_death", entity)
	else:
		_play_at("explosion", entity)
		# Machine power-down chirp layered under the boom (pitch-jittered per kill).
		_play_at_pitched("robot_death", entity, randf_range(0.88, 1.12))


## A machine locked on (calm→CHASE, throttled at the enemy) — positional alert chirp.
func _on_enemy_chase_started(enemy: Node) -> void:
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	if enemy is Node3D:
		_play_at_pitched("robot_alert", enemy, randf_range(0.9, 1.15))


func _on_extraction_started(_player: Node, _zone: Node) -> void:
	_play("extract_beep")


func _on_extraction_completed(_player: Node) -> void:
	_play("extract_done")


func _on_extraction_cancelled(_player: Node) -> void:
	_play("extract_cancel")


func _on_wave_started(_wave_number: int, _enemy_count: int) -> void:
	_play("wave_alert")
	# Raise music slightly while a wave is active.
	if _music_player != null:
		_tween_volume(_music_player, MUSIC_WAVE_DB, 1.5)


func _on_match_won() -> void:
	_play("win")
	_fade_beds_out()


func _on_match_lost() -> void:
	_play("lose")
	_fade_beds_out()


## The STORM hit — crossfade the music bed to the intense evolving loop, a touch
## louder than the wave level. _on_match_started reassigns the normal track, so a
## restart resets this automatically.
func _on_final_wave() -> void:
	if _music_player == null or _streams.get("music_storm") == null:
		return
	var tw := create_tween()
	tw.tween_property(_music_player, "volume_db", -60.0, 1.0)
	tw.tween_callback(_swap_music_storm)
	tw.tween_property(_music_player, "volume_db", MUSIC_WAVE_DB + master_db + 2.0, 2.0)


func _swap_music_storm() -> void:
	var stream: AudioStream = _streams.get("music_storm")
	if stream == null or _music_player == null:
		return
	_set_stream_loop(stream)
	_music_player.stream = stream
	_music_player.play()


# ---------------------------------------------------------------------------
# Event handlers — new
# ---------------------------------------------------------------------------


func _on_reload_started(_weapon_id: String) -> void:
	_play("reload")


func _on_weapon_switched(_weapon_id: String, _ammo: int, _reserve: int) -> void:
	_play("weapon_switch")


func _on_local_player_spawned(player: Node) -> void:
	_local_player = player
	_footstep_timer = 0.0
	_on_match_started()


## Crossfade the looping ambient bed to the local player's biome (urban wind stays the
## fallback when a bed file is absent). Runs on a cheap 2 s poll; render/audio-only.
func _update_biome_bed() -> void:
	if _ambient_player == null or GameState.phase != GameState.Phase.IN_MATCH:
		return
	if not (_local_player is Node3D):
		return
	var pos: Vector3 = (_local_player as Node3D).global_position
	var biome: String = WorldBounds.biome_at(pos.x, pos.z)
	var want: String = _AMB_BY_BIOME.get(biome, "ambient")
	if _streams.get(want) == null:
		want = "ambient"
	if want == _ambient_id:
		return
	_ambient_id = want
	if _amb_tween != null and _amb_tween.is_valid():
		_amb_tween.kill()
	_amb_tween = create_tween()
	_amb_tween.tween_property(_ambient_player, "volume_db", -60.0, 1.2)
	_amb_tween.tween_callback(_swap_ambient_stream.bind(want))
	_amb_tween.tween_property(_ambient_player, "volume_db", AMBIENT_BASE_DB + master_db, 1.8)


func _swap_ambient_stream(id: String) -> void:
	var stream: AudioStream = _streams.get(id)
	if stream == null or _ambient_player == null:
		return
	_set_stream_loop(stream)
	_ambient_player.stream = stream
	_ambient_player.play()


func _on_match_started() -> void:
	if DisplayServer.get_name() == "headless":
		return
	# Start ambient + music beds (the biome poll swaps the bed a moment later).
	_ambient_id = "ambient"
	_amb_poll = 4.0
	if _ambient_player != null and _streams.get("ambient") != null:
		var amb: AudioStream = _streams["ambient"]
		_set_stream_loop(amb)
		_ambient_player.stream = amb
		_ambient_player.volume_db = -80.0
		_ambient_player.play()
		_tween_volume(_ambient_player, AMBIENT_BASE_DB + master_db, 3.0)
	if _music_player != null and _streams.get("music") != null:
		var mus: AudioStream = _streams["music"]
		_set_stream_loop(mus)
		_music_player.stream = mus
		_music_player.volume_db = -80.0
		_music_player.play()
		_tween_volume(_music_player, MUSIC_BASE_DB + master_db, 4.0)


func _on_player_health_changed(player: Node, current: float, max_hp: float) -> void:
	# Only react to the local player.
	if _local_player == null or player != _local_player:
		return
	if max_hp <= 0.0:
		return

	var ratio := current / max_hp
	if ratio < HEARTBEAT_HP_THRESHOLD and current > 0.0:
		# Start/update heartbeat.
		if not _heartbeat_player.playing:
			if _streams.get("heartbeat") != null:
				var hb: AudioStream = _streams["heartbeat"]
				_set_stream_loop(hb)
				_heartbeat_player.stream = hb
				_heartbeat_player.play()
		# Volume and pitch rise as HP falls.
		var urgency := 1.0 - ratio / HEARTBEAT_HP_THRESHOLD  # 0..1
		var target_db: float = float(SOUND_DB.get("heartbeat", -14.0)) + master_db + urgency * 8.0
		_heartbeat_player.volume_db = lerpf(_heartbeat_player.volume_db, target_db, 0.1)
		_heartbeat_player.pitch_scale = 1.0 + urgency * 0.4
	else:
		# Above threshold or dead — stop heartbeat.
		if _heartbeat_player.playing:
			_tween_volume(_heartbeat_player, -80.0, 0.5)
			# Delay stopping so tween can finish.
			get_tree().create_timer(0.6).timeout.connect(
				func() -> void:
					if _heartbeat_player != null:
						_heartbeat_player.stop()
			)


# ---------------------------------------------------------------------------
# Water immersion (Lane B) — muffled audio + ambience while submerged
# ---------------------------------------------------------------------------


## LOCAL water state changed (0 DRY, 1 WADING, 2 SUBMERGED). On SUBMERGED we muffle the
## Master bus (lowpass) + fade in a looping underwater ambience; restored on surface.
## Emitted only by the local authority player, so no remote gating is needed here.
func _on_water_state_changed(state: int, _world_pos: Vector3) -> void:
	if DisplayServer.get_name() == "headless":
		return
	var submerged := state == 2
	if submerged == _underwater_active:
		return
	_underwater_active = submerged
	_set_master_muffle(submerged)
	if _underwater_player == null:
		return
	if submerged:
		if _streams.get("underwater") != null:
			var amb: AudioStream = _streams["underwater"]
			_set_stream_loop(amb)
			if _underwater_player.stream != amb:
				_underwater_player.stream = amb
			if not _underwater_player.playing:
				_underwater_player.play()
			_tween_volume(_underwater_player, UNDERWATER_BASE_DB + master_db, 0.4)
	else:
		_tween_volume(_underwater_player, -80.0, 0.5)


## Add (or remove) a lowpass filter on the Master bus so everything sounds muffled while
## underwater. Idempotent — tracks the effect index it inserted and never duplicates it.
func _set_master_muffle(on: bool) -> void:
	var bus := AudioServer.get_bus_index("Master")
	if bus < 0:
		return
	if on:
		if _underwater_lowpass_idx >= 0:
			return
		var lp := AudioEffectLowPassFilter.new()
		lp.cutoff_hz = 700.0
		AudioServer.add_bus_effect(bus, lp)
		_underwater_lowpass_idx = AudioServer.get_bus_effect_count(bus) - 1
	else:
		if _underwater_lowpass_idx < 0:
			return
		# Remove only if it's still the last effect we added (defensive).
		if _underwater_lowpass_idx < AudioServer.get_bus_effect_count(bus):
			AudioServer.remove_bus_effect(bus, _underwater_lowpass_idx)
		_underwater_lowpass_idx = -1


# ---------------------------------------------------------------------------
# UI button auto-wiring
# ---------------------------------------------------------------------------


func _on_node_added(node: Node) -> void:
	if not (node is BaseButton):
		return
	var btn := node as BaseButton
	if btn.pressed.is_connected(_on_button_pressed):
		return
	btn.pressed.connect(_on_button_pressed)


func _on_button_pressed() -> void:
	_play("ui_click")


## Soft panel-open/close whoosh for UI overlays (map/inventory/modals) — the click
## pitched down so no new asset is needed; open reads higher than close.
func ui_panel(open: bool) -> void:
	_play_pitched("ui_click", 0.8 if open else 0.65, -2.0)


## Skill cast/impact one-shot with a little pitch life (SkillDirector/SkillVFX,
## already distance-gated + headless-skipped upstream).
func play_skill(id: String) -> void:
	_play_pitched(id, randf_range(0.94, 1.06), 0.0)


# ---------------------------------------------------------------------------
# Playback helpers
# ---------------------------------------------------------------------------


## Non-positional one-shot from the round-robin pool.
func _play(id: String) -> void:
	if not enabled:
		return
	var stream: AudioStream = _streams.get(id, null)
	if stream == null:
		return
	var p := _pool[_pool_next]
	_pool_next = (_pool_next + 1) % POOL_SIZE
	p.stream = stream
	p.pitch_scale = 1.0  # reset (a prior _play_pitched on this slot may have changed it)
	p.volume_db = master_db + SOUND_DB.get(id, 0.0)
	p.play()


## Positional one-shot at a Node3D; falls back to the pool for non-3D nodes.
## The AudioStreamPlayer3D is self-freeing so the pool is never starved.
func _play_at(id: String, where: Node) -> void:
	if not enabled:
		return
	var stream: AudioStream = _streams.get(id, null)
	if stream == null:
		return
	if where is Node3D and (where as Node3D).is_inside_tree():
		var p := AudioStreamPlayer3D.new()
		p.stream = stream
		p.bus = "SFX" if _sfx_bus_idx >= 0 else "Master"
		p.volume_db = master_db + SOUND_DB.get(id, 0.0)
		p.max_distance = 60.0
		p.finished.connect(p.queue_free)
		(where as Node3D).add_child(p)
		p.global_position = (where as Node3D).global_position
		p.play()
	else:
		_play(id)


## Positional one-shot with a pitch tweak (variety on repeated crumbles). Mirrors _play_at.
func _play_at_pitched(id: String, where: Node, pitch: float) -> void:
	if not enabled:
		return
	var stream: AudioStream = _streams.get(id, null)
	if stream == null:
		return
	if where is Node3D and (where as Node3D).is_inside_tree():
		var p := AudioStreamPlayer3D.new()
		p.stream = stream
		p.bus = "SFX" if _sfx_bus_idx >= 0 else "Master"
		p.pitch_scale = clampf(pitch, 0.5, 2.0)
		p.volume_db = master_db + SOUND_DB.get(id, 0.0)
		p.max_distance = 60.0
		p.finished.connect(p.queue_free)
		(where as Node3D).add_child(p)
		p.global_position = (where as Node3D).global_position
		p.play()
	else:
		_play(id)


## Creates a dedicated child AudioStreamPlayer with loop mode set.
func _make_looping_player(id: String, vol_db: float) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = "Master"
	p.volume_db = vol_db
	add_child(p)
	# Loop mode is set after the stream is assigned (see _on_match_started).
	# We stash the id so we can re-apply it when the stream is loaded.
	p.set_meta("sound_id", id)
	return p


## Force a stream to loop, regardless of WAV vs Ogg Vorbis backing.
func _set_stream_loop(stream: AudioStream) -> void:
	if stream is AudioStreamWAV:
		(stream as AudioStreamWAV).loop_mode = AudioStreamWAV.LOOP_FORWARD
	elif stream is AudioStreamOggVorbis:
		(stream as AudioStreamOggVorbis).loop = true


## Tween a player's volume_db to target over duration_s.
func _tween_volume(player: AudioStreamPlayer, target_db: float, duration_s: float) -> void:
	var tw := create_tween()
	tw.tween_property(player, "volume_db", target_db, duration_s)


## Fade both ambient and music beds out on match end.
func _fade_beds_out() -> void:
	if _ambient_player != null:
		_tween_volume(_ambient_player, -80.0, 3.0)
	if _music_player != null:
		_tween_volume(_music_player, -80.0, 3.0)
	# Stop heartbeat immediately.
	if _heartbeat_player != null and _heartbeat_player.playing:
		_tween_volume(_heartbeat_player, -80.0, 0.5)
		get_tree().create_timer(0.6).timeout.connect(
			func() -> void:
				if _heartbeat_player != null:
					_heartbeat_player.stop()
		)
	_local_player = null
