extends Node
## Client-side SFX + ambient layer.  Listens to the Events bus and plays
## procedurally-generated WAV sounds in reaction to gameplay.
## Mirrors AssetRegistry's guarded-fallback pattern: a missing file is
## skipped silently so the game ALWAYS runs with zero audio assets.
##
## Audio is purely local: it only reads the (already-replicated) Events
## signals, never networks anything itself.
## HEADLESS SAFETY: all looping bed players + UI-button wiring are
## guarded by DisplayServer.get_name() != "headless" so dedicated servers
## never touch audio hardware.

# ---------------------------------------------------------------------------
# Sound map — logical id -> res path (all .wav; generated by tools/audio/gen_audio.py)
# ---------------------------------------------------------------------------
# Minor SFX (UI/extract/jingles/footsteps/heartbeat/reload/hit/explosion) are CC0
# procedural clips from tools/audio/gen_audio.py. The GUNSHOTS and the two looping
# BEDS (ambient, music) are REAL CC0 recordings fetched by tools/audio/fetch_real_audio.ps1
# (see docs/ASSETS.md → Audio). Per-class gunshots are distinct recorded firearms.
const SOUNDS := {
	# Per-weapon-class gunshots — real CC0 firearm recordings (OpenGameArt "Gunshot Sounds").
	"shot_pistol": "res://assets/audio/shot_pistol.wav",  # CZ-52 pistol
	"shot_rifle": "res://assets/audio/shot_rifle.wav",  # SKS (semi-auto rifle)
	"shot_smg": "res://assets/audio/shot_smg.wav",  # CZ-52 (reused, pitched up)
	"shot_shotgun": "res://assets/audio/shot_shotgun.wav",  # shotgun
	"shot_dmr": "res://assets/audio/shot_dmr.wav",  # Mosin Nagant (bolt-action boom)
	"shot": "res://assets/audio/shot_rifle.wav",  # generic fallback
	"hit": "res://assets/audio/hit.ogg",
	"explosion": "res://assets/audio/explosion.ogg",
	"player_death": "res://assets/audio/player_death.ogg",
	"extract_beep": "res://assets/audio/extract_beep.ogg",
	"extract_done": "res://assets/audio/extract_done.ogg",
	"extract_cancel": "res://assets/audio/extract_cancel.ogg",
	"wave_alert": "res://assets/audio/wave_alert.ogg",
	"win": "res://assets/audio/win.ogg",
	"lose": "res://assets/audio/lose.ogg",
	# New
	"footstep1": "res://assets/audio/footstep1.ogg",
	"footstep2": "res://assets/audio/footstep2.ogg",
	"footstep3": "res://assets/audio/footstep3.ogg",
	"reload": "res://assets/audio/reload.ogg",
	"weapon_switch": "res://assets/audio/weapon_switch.ogg",
	"ui_click": "res://assets/audio/ui_click.ogg",
	"heartbeat": "res://assets/audio/heartbeat.ogg",
	"ambient": "res://assets/audio/ambient.ogg",
	"music": "res://assets/audio/music.ogg",
	# Water immersion (Lane B): entry splash + looping submerged ambience.
	"water_splash": "res://assets/audio/water_splash.ogg",
	"underwater": "res://assets/audio/underwater.ogg",
	# Breakable windows (interactivity overhaul).
	"glass_break": "res://assets/audio/glass_break.wav",
}

## Per-sound volume trim (dB).  Unlisted sounds play at 0 dB.
const SOUND_DB := {
	# Real firearm recordings are hot/peaky — trim them well down so they punch
	# without clipping. Per-class trims layer on top of these (SHOT_CLASS.vol).
	"shot_pistol": -10.0,
	"shot_rifle": -11.0,
	"shot_smg": -12.0,
	"shot_shotgun": -6.0,
	"shot_dmr": -8.0,
	"shot": -11.0,
	"hit": -4.0,
	"explosion": -3.0,
	"player_death": 0.0,
	"win": -2.0,
	"lose": -2.0,
	"footstep1": -12.0,
	"footstep2": -12.0,
	"footstep3": -12.0,
	"reload": -6.0,
	"weapon_switch": -8.0,
	"ui_click": -10.0,
	"heartbeat": -14.0,
	"ambient": -18.0,
	"music": -20.0,
	"water_splash": -5.0,
	"underwater": -12.0,
	"glass_break": -6.0,
}

## Master toggle + trim.  Public so a settings menu can drive them later.
var enabled := true
var master_db := -3.0

# ---------------------------------------------------------------------------
# Shot throttle (weapon_fired fires ~8/s in full auto)
# ---------------------------------------------------------------------------
const SHOT_MIN_INTERVAL := 0.05
var _last_shot_time := -1.0

# ---------------------------------------------------------------------------
# Stream cache (null when the file is absent)
# ---------------------------------------------------------------------------
var _streams: Dictionary = {}

# ---------------------------------------------------------------------------
# Non-positional round-robin pool for one-shot UI / global sounds
# ---------------------------------------------------------------------------
const POOL_SIZE := 8
var _pool: Array[AudioStreamPlayer] = []
var _pool_next := 0

# ---------------------------------------------------------------------------
# Footstep state
# ---------------------------------------------------------------------------
var _local_player: Node = null
var _footstep_timer := 0.0  # countdown to next footstep
const FOOTSTEP_WALK_INTERVAL := 0.50
const FOOTSTEP_SPRINT_INTERVAL := 0.32
const FOOTSTEP_SPEED_THRESHOLD := 1.0  # horizontal m/s below which no footstep

# ---------------------------------------------------------------------------
# Low-HP heartbeat
# ---------------------------------------------------------------------------
var _heartbeat_player: AudioStreamPlayer = null
const HEARTBEAT_HP_THRESHOLD := 0.30  # ratio of max_health

# ---------------------------------------------------------------------------
# Looping ambient + music beds
# ---------------------------------------------------------------------------
var _ambient_player: AudioStreamPlayer = null
var _music_player: AudioStreamPlayer = null
# Underwater ambience bed + Master-bus lowpass for the muffled submerged effect.
var _underwater_player: AudioStreamPlayer = null
var _underwater_lowpass_idx := -1  # index of the lowpass effect we add to Master (-1 = none)
var _underwater_active := false
const UNDERWATER_BASE_DB := -12.0
const AMBIENT_BASE_DB := -19.0  # real wind-loop bed — quiet, atmospheric
const MUSIC_BASE_DB := -23.0  # tense dark-ambient music — deliberately quiet
const MUSIC_WAVE_DB := -18.0  # slight raise during active waves


# ---------------------------------------------------------------------------
# _ready
# ---------------------------------------------------------------------------
func _ready() -> void:
	# Cache streams; absent files resolve to null.
	for id in SOUNDS:
		var path: String = SOUNDS[id]
		if ResourceLoader.exists(path):
			var res := load(path)
			if res is AudioStream:
				_streams[id] = res
				continue
		_streams[id] = null

	# Round-robin pool for non-positional one-shots.
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.bus = "Master"
		add_child(p)
		_pool.append(p)

	# Dedicated looping players (bed tracks + heartbeat).
	_heartbeat_player = _make_looping_player("heartbeat", SOUND_DB.get("heartbeat", 0.0))
	_heartbeat_player.volume_db = -80.0  # start silent
	_heartbeat_player.playing = false

	var is_headless := DisplayServer.get_name() == "headless"

	if not is_headless:
		_ambient_player = _make_looping_player("ambient", AMBIENT_BASE_DB)
		_ambient_player.volume_db = -80.0

		_music_player = _make_looping_player("music", MUSIC_BASE_DB)
		_music_player.volume_db = -80.0

		# Underwater ambience bed (starts silent; faded in on SUBMERGED).
		_underwater_player = _make_looping_player("underwater", UNDERWATER_BASE_DB)
		_underwater_player.volume_db = -80.0

		# Wire UI click to all buttons added after this point.
		get_tree().node_added.connect(_on_node_added)

	# Events bus connections.
	Events.weapon_fired.connect(_on_weapon_fired)
	Events.damage_dealt.connect(_on_damage_dealt)
	Events.entity_died.connect(_on_entity_died)
	Events.extraction_started.connect(_on_extraction_started)
	Events.extraction_completed.connect(_on_extraction_completed)
	Events.extraction_cancelled.connect(_on_extraction_cancelled)
	Events.wave_started.connect(_on_wave_started)
	Events.match_won.connect(_on_match_won)
	Events.match_lost.connect(_on_match_lost)
	Events.grenade_exploded.connect(_on_grenade_exploded)
	Events.reload_started.connect(_on_reload_started)
	Events.weapon_switched.connect(_on_weapon_switched)
	Events.local_player_spawned.connect(_on_local_player_spawned)
	Events.player_health_changed.connect(_on_player_health_changed)
	Events.water_state_changed.connect(_on_water_state_changed)
	Events.glass_broken.connect(_on_glass_broken)
	if Events.has_signal("match_started"):
		Events.match_started.connect(_on_match_started)


# ---------------------------------------------------------------------------
# _process — footstep ticker (independent of player input, reads velocity)
# ---------------------------------------------------------------------------
func _process(delta: float) -> void:
	if not enabled or _local_player == null:
		return
	if not is_instance_valid(_local_player):
		_local_player = null
		return

	# Footstep logic: player must be on the floor and moving.
	if not _local_player.has_method("is_on_floor"):
		return
	if not _local_player.is_on_floor():
		return

	var vel: Vector3 = _local_player.velocity if "velocity" in _local_player else Vector3.ZERO
	var horiz_speed := Vector2(vel.x, vel.z).length()
	if horiz_speed < FOOTSTEP_SPEED_THRESHOLD:
		return

	_footstep_timer -= delta
	if _footstep_timer > 0.0:
		return

	# Pick interval based on speed.
	var is_sprinting := horiz_speed > (Settings.PLAYER_SPRINT_SPEED * 0.6)
	_footstep_timer = FOOTSTEP_SPRINT_INTERVAL if is_sprinting else FOOTSTEP_WALK_INTERVAL

	# Play random variant positionally.
	var variant := "footstep%d" % (randi() % 3 + 1)
	_play_at(variant, _local_player)


# ---------------------------------------------------------------------------
# Event handlers — existing
# ---------------------------------------------------------------------------


func _on_grenade_exploded(_world_pos: Vector3, _damage: float, _radius: float) -> void:
	_play("explosion")


## A window pane shattered (fires on every peer) — positional tinkle at the pane.
func _on_glass_broken(pane: Node) -> void:
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	if pane is Node3D:
		_play_at("glass_break", pane)


## Per-weapon-class gunfire trim. Each class now has its OWN recorded firearm
## (shot_<class>), so this is just a light pitch nudge (SMG reuses the pistol crack,
## pitched up to read snappier) + a small volume trim on top of SOUND_DB. A tiny
## random pitch jitter is applied per shot so repeated fire never sounds identical.
const SHOT_CLASS := {
	"pistol": {"pitch": 1.0, "vol": 0.0},
	"rifle": {"pitch": 1.0, "vol": 0.0},
	"smg": {"pitch": 1.12, "vol": -1.0},
	"shotgun": {"pitch": 0.97, "vol": 0.0},
	"dmr": {"pitch": 0.98, "vol": 0.0},
}


func _on_weapon_fired(_shooter: Node, weapon_id: String) -> void:
	# Entity SFX only while a match runs — a lingering/tearing-down world must never
	# keep shooting sounds into the lobby (UI/extract/win-lose SFX stay ungated).
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	var now := Time.get_ticks_msec() / 1000.0
	if _last_shot_time >= 0.0 and now - _last_shot_time < SHOT_MIN_INTERVAL:
		return
	_last_shot_time = now
	var cfg: Dictionary = SHOT_CLASS.get(weapon_id, SHOT_CLASS["rifle"])
	# Route to the class-specific recorded firearm; fall back to the generic shot if
	# a class file is missing (headless / asset not present).
	var shot_id: String = "shot_" + weapon_id
	if _streams.get(shot_id, null) == null:
		shot_id = "shot"
	_play_pitched(shot_id, float(cfg["pitch"]) * randf_range(0.96, 1.04), float(cfg["vol"]))


## Like _play but with a pitch_scale + extra volume trim (for layered gunfire).
func _play_pitched(id: String, pitch: float, vol_extra: float) -> void:
	if not enabled:
		return
	var stream: AudioStream = _streams.get(id, null)
	if stream == null:
		return
	var p := _pool[_pool_next]
	_pool_next = (_pool_next + 1) % POOL_SIZE
	p.stream = stream
	p.pitch_scale = clampf(pitch, 0.2, 3.0)
	p.volume_db = master_db + SOUND_DB.get(id, 0.0) + vol_extra
	p.play()


func _on_damage_dealt(target: Node, _amount: float, _source: Node) -> void:
	# The lobby "I'm being hit" loop fix, layer 2: damage in a lingering world
	# (post-match teardown, bleed ticks) must never reach the speakers.
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	_play_at("hit", target)


func _on_entity_died(entity: Node, _killer: Node) -> void:
	if GameState.phase != GameState.Phase.IN_MATCH:
		return
	if entity != null and entity.is_in_group(Groups.PLAYERS):
		_play_at("player_death", entity)
	else:
		_play_at("explosion", entity)


func _on_extraction_started(_player: Node, _zone: Node) -> void:
	_play("extract_beep")


func _on_extraction_completed(_player: Node) -> void:
	_play("extract_done")


func _on_extraction_cancelled(_player: Node) -> void:
	_play("extract_cancel")


func _on_wave_started(_wave_number: int, _enemy_count: int) -> void:
	_play("wave_alert")
	# Raise music slightly while a wave is active.
	if _music_player != null:
		_tween_volume(_music_player, MUSIC_WAVE_DB, 1.5)


func _on_match_won() -> void:
	_play("win")
	_fade_beds_out()


func _on_match_lost() -> void:
	_play("lose")
	_fade_beds_out()


# ---------------------------------------------------------------------------
# Event handlers — new
# ---------------------------------------------------------------------------


func _on_reload_started(_weapon_id: String) -> void:
	_play("reload")


func _on_weapon_switched(_weapon_id: String, _ammo: int, _reserve: int) -> void:
	_play("weapon_switch")


func _on_local_player_spawned(player: Node) -> void:
	_local_player = player
	_footstep_timer = 0.0
	_on_match_started()


func _on_match_started() -> void:
	if DisplayServer.get_name() == "headless":
		return
	# Start ambient + music beds.
	if _ambient_player != null and _streams.get("ambient") != null:
		var amb: AudioStream = _streams["ambient"]
		_set_stream_loop(amb)
		_ambient_player.stream = amb
		_ambient_player.volume_db = -80.0
		_ambient_player.play()
		_tween_volume(_ambient_player, AMBIENT_BASE_DB + master_db, 3.0)
	if _music_player != null and _streams.get("music") != null:
		var mus: AudioStream = _streams["music"]
		_set_stream_loop(mus)
		_music_player.stream = mus
		_music_player.volume_db = -80.0
		_music_player.play()
		_tween_volume(_music_player, MUSIC_BASE_DB + master_db, 4.0)


func _on_player_health_changed(player: Node, current: float, max_hp: float) -> void:
	# Only react to the local player.
	if _local_player == null or player != _local_player:
		return
	if max_hp <= 0.0:
		return

	var ratio := current / max_hp
	if ratio < HEARTBEAT_HP_THRESHOLD and current > 0.0:
		# Start/update heartbeat.
		if not _heartbeat_player.playing:
			if _streams.get("heartbeat") != null:
				var hb: AudioStream = _streams["heartbeat"]
				_set_stream_loop(hb)
				_heartbeat_player.stream = hb
				_heartbeat_player.play()
		# Volume and pitch rise as HP falls.
		var urgency := 1.0 - ratio / HEARTBEAT_HP_THRESHOLD  # 0..1
		var target_db: float = float(SOUND_DB.get("heartbeat", -14.0)) + master_db + urgency * 8.0
		_heartbeat_player.volume_db = lerpf(_heartbeat_player.volume_db, target_db, 0.1)
		_heartbeat_player.pitch_scale = 1.0 + urgency * 0.4
	else:
		# Above threshold or dead — stop heartbeat.
		if _heartbeat_player.playing:
			_tween_volume(_heartbeat_player, -80.0, 0.5)
			# Delay stopping so tween can finish.
			get_tree().create_timer(0.6).timeout.connect(
				func() -> void:
					if _heartbeat_player != null:
						_heartbeat_player.stop()
			)


# ---------------------------------------------------------------------------
# Water immersion (Lane B) — muffled audio + ambience while submerged
# ---------------------------------------------------------------------------


## LOCAL water state changed (0 DRY, 1 WADING, 2 SUBMERGED). On SUBMERGED we muffle the
## Master bus (lowpass) + fade in a looping underwater ambience; restored on surface.
## Emitted only by the local authority player, so no remote gating is needed here.
func _on_water_state_changed(state: int, _world_pos: Vector3) -> void:
	if DisplayServer.get_name() == "headless":
		return
	var submerged := state == 2
	if submerged == _underwater_active:
		return
	_underwater_active = submerged
	_set_master_muffle(submerged)
	if _underwater_player == null:
		return
	if submerged:
		if _streams.get("underwater") != null:
			var amb: AudioStream = _streams["underwater"]
			_set_stream_loop(amb)
			if _underwater_player.stream != amb:
				_underwater_player.stream = amb
			if not _underwater_player.playing:
				_underwater_player.play()
			_tween_volume(_underwater_player, UNDERWATER_BASE_DB + master_db, 0.4)
	else:
		_tween_volume(_underwater_player, -80.0, 0.5)


## Add (or remove) a lowpass filter on the Master bus so everything sounds muffled while
## underwater. Idempotent — tracks the effect index it inserted and never duplicates it.
func _set_master_muffle(on: bool) -> void:
	var bus := AudioServer.get_bus_index("Master")
	if bus < 0:
		return
	if on:
		if _underwater_lowpass_idx >= 0:
			return
		var lp := AudioEffectLowPassFilter.new()
		lp.cutoff_hz = 700.0
		AudioServer.add_bus_effect(bus, lp)
		_underwater_lowpass_idx = AudioServer.get_bus_effect_count(bus) - 1
	else:
		if _underwater_lowpass_idx < 0:
			return
		# Remove only if it's still the last effect we added (defensive).
		if _underwater_lowpass_idx < AudioServer.get_bus_effect_count(bus):
			AudioServer.remove_bus_effect(bus, _underwater_lowpass_idx)
		_underwater_lowpass_idx = -1


# ---------------------------------------------------------------------------
# UI button auto-wiring
# ---------------------------------------------------------------------------


func _on_node_added(node: Node) -> void:
	if not (node is BaseButton):
		return
	var btn := node as BaseButton
	if btn.pressed.is_connected(_on_button_pressed):
		return
	btn.pressed.connect(_on_button_pressed)


func _on_button_pressed() -> void:
	_play("ui_click")


# ---------------------------------------------------------------------------
# Playback helpers
# ---------------------------------------------------------------------------


## Non-positional one-shot from the round-robin pool.
func _play(id: String) -> void:
	if not enabled:
		return
	var stream: AudioStream = _streams.get(id, null)
	if stream == null:
		return
	var p := _pool[_pool_next]
	_pool_next = (_pool_next + 1) % POOL_SIZE
	p.stream = stream
	p.pitch_scale = 1.0  # reset (a prior _play_pitched on this slot may have changed it)
	p.volume_db = master_db + SOUND_DB.get(id, 0.0)
	p.play()


## Positional one-shot at a Node3D; falls back to the pool for non-3D nodes.
## The AudioStreamPlayer3D is self-freeing so the pool is never starved.
func _play_at(id: String, where: Node) -> void:
	if not enabled:
		return
	var stream: AudioStream = _streams.get(id, null)
	if stream == null:
		return
	if where is Node3D and (where as Node3D).is_inside_tree():
		var p := AudioStreamPlayer3D.new()
		p.stream = stream
		p.bus = "Master"
		p.volume_db = master_db + SOUND_DB.get(id, 0.0)
		p.max_distance = 60.0
		p.finished.connect(p.queue_free)
		(where as Node3D).add_child(p)
		p.global_position = (where as Node3D).global_position
		p.play()
	else:
		_play(id)


## Creates a dedicated child AudioStreamPlayer with loop mode set.
func _make_looping_player(id: String, vol_db: float) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = "Master"
	p.volume_db = vol_db
	add_child(p)
	# Loop mode is set after the stream is assigned (see _on_match_started).
	# We stash the id so we can re-apply it when the stream is loaded.
	p.set_meta("sound_id", id)
	return p


## Force a stream to loop, regardless of WAV vs Ogg Vorbis backing.
func _set_stream_loop(stream: AudioStream) -> void:
	if stream is AudioStreamWAV:
		(stream as AudioStreamWAV).loop_mode = AudioStreamWAV.LOOP_FORWARD
	elif stream is AudioStreamOggVorbis:
		(stream as AudioStreamOggVorbis).loop = true


## Tween a player's volume_db to target over duration_s.
func _tween_volume(player: AudioStreamPlayer, target_db: float, duration_s: float) -> void:
	var tw := create_tween()
	tw.tween_property(player, "volume_db", target_db, duration_s)


## Fade both ambient and music beds out on match end.
func _fade_beds_out() -> void:
	if _ambient_player != null:
		_tween_volume(_ambient_player, -80.0, 3.0)
	if _music_player != null:
		_tween_volume(_music_player, -80.0, 3.0)
	# Stop heartbeat immediately.
	if _heartbeat_player != null and _heartbeat_player.playing:
		_tween_volume(_heartbeat_player, -80.0, 0.5)
		get_tree().create_timer(0.6).timeout.connect(
			func() -> void:
				if _heartbeat_player != null:
					_heartbeat_player.stop()
		)
	_local_player = null
