extends RefCounted
class_name ResourceIndex
## GENERATED by tools/build/export_windows.ps1 — explicit .tres paths so the catalogs
## work in EXPORTED builds (DirAccess can't enumerate a res:// dir inside a PCK).
## Do not hand-edit.

const ITEMS: PackedStringArray = [
	"res://resources/items/ammo_box.tres",
	"res://resources/items/artifact.tres",
	"res://resources/items/chemicals.tres",
	"res://resources/items/circuit_pack.tres",
	"res://resources/items/circuit.tres",
	"res://resources/items/data_chip.tres",
	"res://resources/items/energy_cell.tres",
	"res://resources/items/grenade_mk2.tres",
	"res://resources/items/grenade.tres",
	"res://resources/items/medkit.tres",
	"res://resources/items/plastic.tres",
	"res://resources/items/rifle.tres",
	"res://resources/items/schematic_ammo.tres",
	"res://resources/items/schematic_circuit_pack.tres",
	"res://resources/items/schematic_drum_mag.tres",
	"res://resources/items/schematic_grenade_mk2.tres",
	"res://resources/items/schematic_stim.tres",
	"res://resources/items/schematic_suppressor.tres",
	"res://resources/items/scrap.tres",
	"res://resources/items/stim.tres",
]

const ATTACHMENTS: PackedStringArray = [
	"res://resources/attachments/att_compensator.tres",
	"res://resources/attachments/att_drum_mag.tres",
	"res://resources/attachments/att_ext_mag.tres",
	"res://resources/attachments/att_heavy_grip.tres",
	"res://resources/attachments/att_holo_sight.tres",
	"res://resources/attachments/att_light_mag.tres",
	"res://resources/attachments/att_long_barrel.tres",
	"res://resources/attachments/att_quickdraw_grip.tres",
	"res://resources/attachments/att_red_dot.tres",
	"res://resources/attachments/att_scope_4x.tres",
	"res://resources/attachments/att_suppressor.tres",
]

const RECIPES: PackedStringArray = [
	"res://resources/recipes/recipe_ammo.tres",
	"res://resources/recipes/recipe_bulk_medkit.tres",
	"res://resources/recipes/recipe_circuit_pack.tres",
	"res://resources/recipes/recipe_data_chip_recycle.tres",
	"res://resources/recipes/recipe_drum_mag.tres",
	"res://resources/recipes/recipe_grenade_mk2.tres",
	"res://resources/recipes/recipe_grenade.tres",
	"res://resources/recipes/recipe_medkit.tres",
	"res://resources/recipes/recipe_plastic_to_cell.tres",
	"res://resources/recipes/recipe_red_dot.tres",
	"res://resources/recipes/recipe_scrap_to_plastic.tres",
	"res://resources/recipes/recipe_stim.tres",
	"res://resources/recipes/recipe_suppressor.tres",
]

const QUESTS: PackedStringArray = [
	"res://resources/quests/daily_extract_item.tres",
	"res://resources/quests/daily_extract.tres",
	"res://resources/quests/daily_heavy_killer.tres",
	"res://resources/quests/daily_kills.tres",
	"res://resources/quests/daily_loot_hunter.tres",
	"res://resources/quests/daily_wave_survivor.tres",
	"res://resources/quests/quest_extract_artifact.tres",
	"res://resources/quests/quest_extract.tres",
	"res://resources/quests/quest_kill_boss.tres",
	"res://resources/quests/quest_kill_wasp.tres",
	"res://resources/quests/quest_kills.tres",
	"res://resources/quests/quest_pickup_data_chip.tres",
	"res://resources/quests/quest_reach_wave5.tres",
	"res://resources/quests/standing_boss_hunter.tres",
	"res://resources/quests/standing_chiprunner.tres",
	"res://resources/quests/standing_wave_veteran.tres",
]

